version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
    - '27017:27017'
    env_file:
      - .env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
  redis:    
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81   
    env_file:
      - .env
    # environment:
    #   REDIS_PORT: 6379
    #   REDIS_PASSWORD: example
